name: Track releases from Pypi

on:
  push:

env:
  IMAGE_NAME: git-packages-test

jobs:
  job1:
    name: Check Pypi Packages Latetest Releases
    runs-on: ubuntu-latest

    outputs:
      script: ${{ steps.script-pypi.outputs }}

    steps:
      - name: checkout repo content
        id: checkout
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        id: setup-py
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script
        id: script-pypi
        run: python check_pypi_versions.py


  job2:
    name: "Create PR to Bump Package"
    runs-on: ubuntu-latest

    needs: job1
    steps:
      - name: create PR
        id: test
        run: echo ${{needs.job1.outputs.script}}

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Teste
          body: |
            ## This week's TODO

            - [ ] Have a meeting with UX team
            - [ ] Check the dashboard
