name: Track releases from Pypi

on:
  push:

# on:
#   schedule:
#     - cron: '0 9 * * MON' # Every monday

jobs:
  check_pypi_versions:
    name: Check Pypi Packages Latest Releases
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.script-pypi.outputs.packages }}

    steps:
      - name: checkout repo content
        id: checkout
        uses: actions/checkout@v2

      - name: setup python
        id: setup-py
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script
        id: script-pypi
        run: |
          output=$(python check_pypi_versions.py)
          echo "::set-output name=packages::$output"


  github_actions:
    name: "Create Issue to Bump Package"
    runs-on: ubuntu-latest

    needs: check_pypi_versions


    strategy:
        fail-fast: false
        matrix:
            packages: ${{fromJson(needs.check_pypi_versions.outputs.packages)}}

    steps:
      - name: Create an Issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Must Bump Package => ${{ matrix.packages.package }}
          body: |
            Package to Bump: ${{ matrix.packages.package }}
            To Version: ${{ matrix.packages.bump_to }}

            Done by Github Actions.
